modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/ChocoBooyy/Create-Henry/issues"

[[mods]]
    modId="create_henry"
    version="${file.jarVersion}"
    displayName="Create: Henry"
    displayURL="https://modrinth.com/mod/create-henry"
    logoFile= "pack.png"
    credits="LopyLuna"
    authors="ChocoBoy, TryMyWagon, LopyLuna"
    description='''
Create: Henry is an addon for the Create mod that add random QoL, items, & blocks features that relates to old Create & New Create versions! It is also a continued version of the addon "Create: Dreams & Desires" for 1.20.1.
'''

[[dependencies.create_henry]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_henry]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_henry]]
    modId="create"
    mandatory=true
    versionRange="[0.5.1.f,)"
    ordering="AFTER"
    side="BOTH"
